import { registerLooplanComponents } from './components';
import { JsDataType } from './lib/data-type';
import { resolveComponent } from './lib/component';
import { createApi } from './api';
import type { App } from 'vue';
import { gatewayOptions, setGateway, getComponentPackage } from './loader/component/lib/ComponentGateway';
import { setComponentPackage, registerPackage, loadComponent, asyncComponentDelay, nameIsUseAsyncComponent, getComponentOption, loadStyle, unloadStyle, isStyleLoaded, getLoadedStyles, unloadAllStyles } from '@/loader/component';
import { iconGatewayOptions, setIconGateway, getIconPackage } from './components/lp-icon/lib/IconGateway';
import { loadIcon, setIconPackage, IconPackages, mountIconfont, unmountIconfont } from './components/lp-icon/lib/index';
import { LpComponent } from './components/lp-component';
import { LpIcon, LpSvg } from './components/lp-icon';
import { LooplanException } from './exception/LooplanException';
import ModelClient from './loader/data/ModelClient';
import ModelSpace from './loader/data/ModelSpace';
declare function install(app: App): void;
export type { ComponentOption, LoadedModule, ComponentPackageConfig } from '@/types/component';
export type { GatewayOption } from '@/types/index';
export type { IconPackageConfig } from '@/components/lp-icon/types/index';
export type { ListSortType, listApiResult, PaginateApiResult, PaginatePageStatus, PaginateXOptions, PaginateXApiResult, PaginateXPageStatus, } from '@/types/model-client';
export { LooplanException, install, LpComponent, LpIcon, LpSvg, createApi, JsDataType, registerLooplanComponents, setComponentPackage, registerPackage, loadComponent, asyncComponentDelay, nameIsUseAsyncComponent, getComponentOption, loadStyle, unloadStyle, isStyleLoaded, getLoadedStyles, unloadAllStyles, gatewayOptions, setGateway, getComponentPackage, loadIcon, setIconPackage, IconPackages, mountIconfont, unmountIconfont, iconGatewayOptions, setIconGateway, getIconPackage, resolveComponent, ModelSpace, ModelClient, };
declare const _default: {
    install: typeof install;
};
export default _default;
